-- CreateEnum
CREATE TYPE "RoleEnum" AS ENUM ('USER', 'ADMIN');

-- CreateEnum
CREATE TYPE "StatusEnum" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "RequestTypesEnum" AS ENUM ('ATIVIDADE_COMPLEMENTAR', 'DISPENSA_DISCIPLINA', 'RESERVA_SALA', 'EMISSAO_CRACHA', 'AJUSTE_COTAS', 'PROBLEMAS_TECNICOS');

-- CreateTable
CREATE TABLE "TB_USER" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "refreshToken" VARCHAR(100) NOT NULL,
    "cpf" VARCHAR(11) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "role" "RoleEnum" NOT NULL,
    "status" "StatusEnum" NOT NULL,
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "TB_USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_USER_SECTOR" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "sectorId" INTEGER NOT NULL,

    CONSTRAINT "TB_USER_SECTOR_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_SECTOR" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "status" "StatusEnum" NOT NULL,
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "TB_SECTOR_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_DEMAND" (
    "id" SERIAL NOT NULL,
    "requestedType" "RequestTypesEnum" NOT NULL,
    "status" "StatusEnum" NOT NULL,
    "text" TEXT NOT NULL,
    "sectorId" INTEGER,
    "userId" INTEGER,
    "updatedAt" TIMESTAMP(3),
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_DEMAND_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_DEMAND_STATUS_REQUEST" (
    "id" SERIAL NOT NULL,
    "information" TEXT NOT NULL,
    "mediaId" INTEGER,
    "demandId" INTEGER,
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_DEMAND_STATUS_REQUEST_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_MEDIA" (
    "id" SERIAL NOT NULL,
    "url" VARCHAR(500) NOT NULL,
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_MEDIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_CONFIGURATION" (
    "id" SERIAL NOT NULL,
    "key" VARCHAR(255) NOT NULL,
    "value" VARCHAR(255) NOT NULL,
    "createdDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "TB_CONFIGURATION_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_USER_cpf_key" ON "TB_USER"("cpf");

-- CreateIndex
CREATE UNIQUE INDEX "TB_USER_email_key" ON "TB_USER"("email");

-- AddForeignKey
ALTER TABLE "TB_USER_SECTOR" ADD CONSTRAINT "TB_USER_SECTOR_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_USER_SECTOR" ADD CONSTRAINT "TB_USER_SECTOR_sectorId_fkey" FOREIGN KEY ("sectorId") REFERENCES "TB_SECTOR"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_DEMAND" ADD CONSTRAINT "TB_DEMAND_sectorId_fkey" FOREIGN KEY ("sectorId") REFERENCES "TB_SECTOR"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_DEMAND" ADD CONSTRAINT "TB_DEMAND_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_DEMAND_STATUS_REQUEST" ADD CONSTRAINT "TB_DEMAND_STATUS_REQUEST_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "TB_MEDIA"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_DEMAND_STATUS_REQUEST" ADD CONSTRAINT "TB_DEMAND_STATUS_REQUEST_demandId_fkey" FOREIGN KEY ("demandId") REFERENCES "TB_DEMAND"("id") ON DELETE SET NULL ON UPDATE CASCADE;
